Running time: 2.826161598 seconds

Traceback (most recent call last):
  File "securify/__main__.py", line 286, in <module>
    main()
  File "securify/__main__.py", line 277, in main
    matches.extend(pattern.find_matches())
  File "/sec/securify/analyses/patterns/ast/state_variables_default_visibility.py", line 21, in find_matches
    ast_root = self.get_ast_root()
  File "/sec/securify/analyses/patterns/ast/abstract_ast_pattern.py", line 18, in get_ast_root
    ast_root = self.analysis_context.ast
  File "/sec/securify/analyses/analysis.py", line 74, in ast
    self._ast = self.config.ast_compiler(self)
  File "securify/__main__.py", line 253, in <lambda>
    ast_compiler=lambda t: solidity_ast_compiler.compile_ast(t.source_file),
  File "/sec/securify/solidity/solidity_ast_compiler.py", line 31, in compile_ast
    compile_output = compile_standard(compile_input, allow_paths='/')
  File "/usr/local/lib/python3.7/dist-packages/py_solc-3.2.0-py3.7.egg/solc/main.py", line 181, in compile_standard
    message=error_message,
solc.exceptions.SolcError: unused_state_variables.sol:4:1: ParserError: Source "base.sol" not found: File outside of allowed directories.
import "./base.sol";
^------------------^

        > command: `solc --allow-paths / --standard-json`
        > return code: `0`
        > stderr:
        {"errors":[{"component":"general","formattedMessage":"unused_state_variables.sol:4:1: ParserError: Source \"base.sol\" not found: File outside of allowed directories.
import \"./base.sol\";
^------------------^
","message":"Source \"base.sol\" not found: File outside of allowed directories.","severity":"error","sourceLocation":{"end":80,"file":"unused_state_variables.sol","start":60},"type":"ParserError"}],"sources":{}}

        > stdout:
